let times = [
        [
            [null],
            [null],
            [null],
            [null],
            [null],
            [null],
            [null]
        ],
        [
            [null],
            [null],
            [null],
            [null],
            [null],
            [null],
            [null]
        ],
        [
            [null],
            [null],
            [null],
            [null],
            [null],
            [null],
            [null]
        ],
        [
            [null],
            [null],
            [null],
            [null],
            [null],
            [null],
            [null]
        ],
        [
            [null],
            [null],
            [null],
            [null],
            [null],
            [null],
            [null]
        ],
        [
            [null],
            [null],
            [null],
            [null],
            [null],
            [null],
            [null]
        ],
        [
            [null],
            [null],
            [null],
            [null],
            [null],
            [null],
            [null]
        ]
    ]

module.exports = { times };